void printSentence(char * message, int x, int y, int len);
void ClearScreen();
char * getInput();
void shutdown();
void dispatch(int address, int size);
void reboot();
void clear();
char * getManual();
char * getDate();
void roll();